---
title: "Brazil Raster Builder"
author: "Nick McManus"
date: "2023-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(terra)     #GIS
library(geobr)     #administrative boundaries for Brazil
library(tidyverse) #always
library(here)      #reading/writing data easier
```

# OVERVIEW:

This markdown first finds areas of projected cropland abandonment in Brazil between the years 2020 to 2050, then crops, masks, and resamples biodiversity and carbon data to match the spatial extent of the cropland abandonment rasters. Land use and land cover (LULC) data sourced from Chen et al. 2022. This dataset includes projected LULC under different shared socioeconomic pathways (SSPs) as well as a baseline LULC data from 2015. The outputs from this code — rasters containing every pixel of projected abandonment between 2020-2050 for a given SSP — will be utilized for further analysis of restoration optimization in the corresponding `prioritizr` markdown of this repository. Output rasters from this code populate in the `data/processed/brazil` repository folder; this are called into the Shiny App. More information on the source data can be found in the project README.md file. 



# CROPLAND ABANDONMENT:




# BIODIVERSITY:



# CARBON: